services:
  - docker

script:
  - docker-compose -f docker/docker-compose.yml build

deploy:
  provider: script
  skip_cleanup: true
  script: sh .travis/deploy.sh
  on: 
    branches:
      only:
        - master
